#!/usr/bin/env sh
set -eu

failures=0

require_file() {
  if [ ! -f "$1" ]; then
    printf 'missing file: %s\n' "$1"
    failures=$((failures + 1))
  fi
}

require_text() {
  file="$1"
  text="$2"
  label="$3"

  if [ ! -f "$file" ]; then
    printf 'missing file for text check: %s\n' "$file"
    failures=$((failures + 1))
    return
  fi

  if ! grep -F "$text" "$file" >/dev/null 2>&1; then
    printf 'missing text: %s in %s\n' "$label" "$file"
    failures=$((failures + 1))
  fi
}

require_file "README.md"
require_file "global/harness/README.md"
require_file "global/harness/architecture.md"
require_file "global/harness/deliberation.md"
require_file "global/harness/schemas/fixture.schema.json"
require_file "global/harness/schemas/run-record.schema.json"
require_file "global/harness/fixtures/core.json"
require_file "scripts/validate-harness.mjs"
require_file "scripts/evaluate-run.mjs"
require_file "scripts/test-evaluator.mjs"
require_file "global/harness/runs/blueprint_payment_retry.pass.json"
require_file "global/harness/runs/destructive_reset_request.fail.json"
require_file "AGENTS.md"
require_file "CLAUDE.md"
require_file "global/models/codex/README.md"
require_file "global/models/codex/AGENT.md"
require_file "global/models/codex/context-map.md"
require_file "global/models/codex/project-rules.md"
require_file "global/models/codex/validation.md"
require_file "global/models/codex/handoff-log.md"
require_file "global/models/codex/handoff-archive.md"
require_file "global/models/codex/harness/README.md"
require_file "global/models/codex/harness/state-machine.md"
require_file "global/models/codex/harness/failure-cases.md"
require_file "global/models/codex/harness/output-schema.md"
require_file "global/models/codex/harness/fixtures.md"
require_file "global/models/codex/harness/evaluation-rubric.md"
require_file "local/README.md"
require_file "local/_template/domain-policy.md"
require_file "local/_template/architecture.md"
require_file "local/_template/goal.md"
require_file "local/_template/context-map.md"
require_file "local/_template/tools.md"
require_file "local/_template/validation.md"
require_file "local/_template/handoff-log.md"
require_file "local/sample-project/goal.md"
require_file "local/sample-project/context-map.md"
require_file "local/sample-project/domain-policy.md"
require_file "local/sample-project/architecture.md"
require_file "local/sample-project/validation.md"
require_file "local/sample-project/handoff-log.md"

require_file "global/models/claude/README.md"
require_file "global/models/claude/AGENT.md"
require_file "global/models/claude/context-map.md"
require_file "global/models/claude/goal.md"
require_file "global/models/claude/domain-rules.md"
require_file "global/models/claude/model-routing.md"
require_file "global/models/claude/project-rules.md"
require_file "global/models/claude/roles.md"
require_file "global/models/claude/tools.md"
require_file "global/models/claude/validation.md"
require_file "global/models/claude/handoff-log.md"
require_file "global/models/claude/handoff-archive.md"
require_file "global/models/claude/harness/README.md"
require_file "global/models/claude/harness/state-machine.md"
require_file "global/models/claude/harness/failure-cases.md"
require_file "global/models/claude/harness/output-schema.md"
require_file "global/models/claude/harness/fixtures.md"
require_file "global/models/claude/harness/evaluation-rubric.md"

require_text "README.md" "./global/models/codex/harness/README.md" "root harness link"
require_text "README.md" "./global/harness/README.md" "shared harness link"
require_text "README.md" "global/harness/deliberation.md" "shared deliberation link"
require_text "global/harness/architecture.md" "## 종료 조건" "shared harness termination rules"
require_text "global/harness/architecture.md" "## Human-in-the-loop" "shared harness human approval rules"
require_text "global/harness/architecture.md" "deliberation.md" "shared deliberation architecture reference"
require_text "global/harness/README.md" "run-record.schema.json" "shared run record reference"
require_text "global/harness/README.md" "deliberation.md" "shared deliberation readme reference"
require_text "global/harness/deliberation.md" "## 라운드" "shared deliberation rounds"
require_text "global/harness/deliberation.md" "## 산출물 형식" "shared deliberation output schema"
require_text "global/harness/deliberation.md" "## 라운드 요약 로그" "shared deliberation summary log"
require_text "AGENTS.md" "global/models/codex/AGENT.md" "codex entry pointer"
require_text "README.md" "./global/models/claude/README.md" "root claude model link"
require_text "README.md" "./global/models/claude/harness/README.md" "root claude harness link"
require_text "README.md" "project-rules.md" "root project rules reference"
require_text "global/models/codex/README.md" "./harness/README.md" "codex harness link"
require_text "global/models/codex/context-map.md" "Harness Documents" "harness context section"
require_text "global/models/codex/validation.md" "## 하네스 검증" "harness validation section"
require_text "global/models/codex/handoff-log.md" "handoff-archive.md" "codex handoff archive rule"
require_text "global/models/codex/project-rules.md" "handoff-archive.md" "codex project handoff archive mention"
require_text "global/models/codex/validation.md" "handoff-archive.md" "codex handoff archive validation"
require_text "global/models/codex/validation.md" "## UI/프론트엔드 변경 검증" "codex ui validation section"
require_text "global/models/codex/model-routing.md" ".codex/agents/<name>.toml" "codex custom agent TOML rule"
require_text "global/models/codex/model-routing.md" "model_reasoning_effort" "codex reasoning effort setting"
require_text "global/models/codex/model-routing.md" "deliberation.md" "codex deliberation routing"
require_text "global/models/codex/AGENT.md" "안전한 진단 명령" "codex read-only planning boundary"
require_text "global/models/codex/harness/README.md" "state-machine.md" "state machine reference"
require_text "global/models/codex/harness/README.md" "failure-cases.md" "failure cases reference"
require_text "global/models/codex/harness/README.md" "output-schema.md" "output schema reference"
require_text "global/models/codex/harness/README.md" "fixtures.md" "fixtures reference"
require_text "global/models/codex/harness/README.md" "evaluation-rubric.md" "evaluation rubric reference"
require_text "global/models/codex/context-map.md" "evaluation-rubric.md" "evaluation rubric context reference"
require_text "global/models/codex/validation.md" "evaluation-rubric.md" "evaluation rubric validation reference"
require_text "global/models/codex/README.md" "./project-rules.md" "project rules readme reference"
require_text "global/models/codex/AGENT.md" "project-rules.md" "project rules agent reference"
require_text "global/models/codex/context-map.md" "project-rules.md" "project rules context reference"
require_text "global/models/codex/validation.md" "## 프로젝트 하네스 검증" "project harness validation section"
require_text "global/models/codex/validation.md" "## 숙의형 멀티 에이전트 검증" "codex deliberation validation"
require_text "global/models/codex/harness/output-schema.md" "## 로컬 하네스 대화 산출물" "local harness dialog schema"
require_text "global/models/codex/harness/output-schema.md" "architecture_policy" "codex architecture policy output"
require_text "global/models/codex/harness/output-schema.md" "architecture_blueprint" "codex architecture blueprint output"
require_text "global/models/codex/harness/output-schema.md" "## 프로젝트 생성 결과 산출물" "project creation result schema"
require_text "global/models/codex/harness/fixtures.md" "Fixture 10" "project bootstrap fixture"
require_text "global/models/codex/harness/fixtures.md" "프로젝트 경로" "project report fields fixture"
require_text "global/models/codex/harness/fixtures.md" "architecture.md" "codex architecture fixture"
require_text "global/models/codex/harness/evaluation-rubric.md" "project_bootstrap" "project bootstrap request type"
require_text "global/models/codex/harness/failure-cases.md" "프로젝트 하네스 위반" "project harness failure section"
require_text "global/models/codex/harness/failure-cases.md" "architecture.md" "codex architecture failure"
require_text "global/models/codex/project-rules.md" "새 프로젝트 기본 완료 체크리스트" "project completion checklist"
require_text "global/models/codex/project-rules.md" "프로젝트 유형별 최소 기준" "project type minimums"
require_text "global/models/codex/project-rules.md" "로컬 하네스 작성 품질 기준" "local harness quality criteria"
require_text "global/models/codex/project-rules.md" "architecture.md" "codex architecture local harness"
require_text "global/models/codex/project-rules.md" "local/_template/" "local template reference"
require_text "global/models/codex/validation.md" "유형별 최소 기준" "project type validation"
require_text "global/models/codex/validation.md" "## 아키텍처 청사진 검증" "codex architecture validation"
require_text "local/_template/goal.md" "## 완료 기준" "goal template completion section"
require_text "local/_template/context-map.md" "## 먼저 확인할 위치" "context template first locations"
require_text "local/_template/architecture.md" "## 기술 스택" "architecture template stack section"
require_text "local/_template/architecture.md" "## 변경 가능성" "architecture template changeability section"
require_text "local/_template/tools.md" "## 승인 필요한 작업" "tools template approval section"
require_text "local/_template/validation.md" "## 검증 보고 기준" "validation template report section"
require_text "local/_template/handoff-log.md" "## 현재 기록" "handoff template current log"
require_text "global/models/codex/AGENT.md" "청사진, 계획, 설계만 요청" "blueprint-only boundary"
require_text "global/models/codex/AGENT.md" "구현, 수정, 실행을 명확히 요청" "implementation boundary"
require_text "global/models/codex/roles.md" "동작 변경에는 TDD" "behavior-change TDD boundary"
require_text "global/models/codex/harness/output-schema.md" "인계 가치가 낮은 작업은 최종 보고" "conditional handoff rule"
require_text "global/models/codex/harness/fixtures.md" "Fixture 9" "html javascript fixture"
require_text "local/README.md" "./sample-project/" "sample project link"
require_text "local/README.md" "architecture.md" "local architecture document"
require_text "local/sample-project/domain-policy.md" "Badge" "sample domain concept"
require_text "local/sample-project/architecture.md" "## 애플리케이션 구조" "sample architecture structure"

require_text "global/models/claude/README.md" "./harness/README.md" "claude harness link"
require_text "global/models/claude/README.md" "./project-rules.md" "project rules claude readme reference"
require_text "global/models/claude/context-map.md" "Harness Documents" "claude harness context section"
require_text "global/models/claude/context-map.md" "project-rules.md" "project rules claude context reference"
require_text "global/models/claude/context-map.md" "evaluation-rubric.md" "evaluation rubric claude context reference"
require_text "global/models/claude/validation.md" "## 하네스 검증" "claude harness validation section"
require_text "global/models/claude/validation.md" "## 프로젝트 하네스 검증" "project harness claude validation section"
require_text "global/models/claude/validation.md" "evaluation-rubric.md" "evaluation rubric claude validation reference"
require_text "global/models/claude/harness/README.md" "state-machine.md" "claude state machine reference"
require_text "global/models/claude/harness/README.md" "failure-cases.md" "claude failure cases reference"
require_text "global/models/claude/harness/README.md" "output-schema.md" "claude output schema reference"
require_text "global/models/claude/harness/README.md" "fixtures.md" "claude fixtures reference"
require_text "global/models/claude/harness/README.md" "evaluation-rubric.md" "claude evaluation rubric reference"
require_text "global/models/claude/harness/output-schema.md" "## 로컬 하네스 대화 산출물" "claude local harness dialog schema"
require_text "global/models/claude/harness/output-schema.md" "architecture_policy" "claude architecture policy output"
require_text "global/models/claude/harness/output-schema.md" "architecture_blueprint" "claude architecture blueprint output"
require_text "global/models/claude/harness/output-schema.md" "## 프로젝트 생성 결과 산출물" "claude project creation result schema"
require_text "global/models/claude/harness/output-schema.md" "인계 가치가 낮은 작업은 최종 보고" "claude conditional handoff rule"
require_text "global/models/claude/harness/fixtures.md" "Fixture 10" "claude project bootstrap fixture"
require_text "global/models/claude/harness/fixtures.md" "Fixture 11" "claude orchestration opt-in fixture"
require_text "global/models/claude/harness/fixtures.md" "프로젝트 경로" "claude project report fields fixture"
require_text "global/models/claude/harness/fixtures.md" "architecture.md" "claude architecture fixture"
require_text "global/models/claude/harness/evaluation-rubric.md" "project_bootstrap" "claude project bootstrap request type"
require_text "global/models/claude/harness/failure-cases.md" "프로젝트 하네스 위반" "claude project harness failure section"
require_text "global/models/claude/harness/failure-cases.md" "architecture.md" "claude architecture failure"
require_text "global/models/claude/project-rules.md" "새 프로젝트 기본 완료 체크리스트" "claude project completion checklist"
require_text "global/models/claude/project-rules.md" "프로젝트 유형별 최소 기준" "claude project type minimums"
require_text "global/models/claude/project-rules.md" "로컬 하네스 작성 품질 기준" "claude local harness quality criteria"
require_text "global/models/claude/project-rules.md" "architecture.md" "claude architecture local harness"
require_text "global/models/claude/project-rules.md" "local/_template/" "claude local template reference"
require_text "global/models/claude/validation.md" "## 아키텍처 청사진 검증" "claude architecture validation"
require_text "global/models/claude/AGENT.md" "청사진, 계획, 설계만 요청" "claude blueprint-only boundary"
require_text "global/models/claude/AGENT.md" "구현, 수정, 실행을 명확히 요청" "claude implementation boundary"
require_text "global/models/claude/roles.md" "동작 변경에는 TDD" "claude behavior-change TDD boundary"
require_text "global/models/claude/model-routing.md" "type" "claude no type field rule"
require_text "global/models/claude/model-routing.md" "Workflow" "claude workflow opt-in rule"
require_text "global/models/claude/model-routing.md" "deliberation.md" "claude deliberation routing"
require_text "global/models/claude/validation.md" "## 숙의형 멀티 에이전트 검증" "claude deliberation validation"

require_text "CLAUDE.md" "global/models/claude/AGENT.md" "claude entry pointer"
require_text "global/models/claude/handoff-log.md" "handoff-archive.md" "claude handoff archive rule"
require_text "local/_template/handoff-log.md" "handoff-archive.md" "template handoff archive rule"
require_text "local/sample-project/handoff-log.md" "handoff-archive.md" "sample handoff archive rule"
require_text "global/models/claude/project-rules.md" "handoff-archive.md" "project rules handoff archive mention"
require_text "global/models/claude/validation.md" "handoff-archive.md" "validation handoff archive check"
require_text "global/models/claude/context-map.md" "Explore" "context map explore delegation"
require_text "local/_template/context-map.md" "실제 파일 경로" "template concrete entrypoint guidance"

if [ "$failures" -ne 0 ]; then
  printf 'document validation failed: %s issue(s)\n' "$failures"
  exit 1
fi

printf 'document validation passed\n'
